package sandbox

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"
)

// AppOptions describes how to bring the project's own API up against the sandbox.
type AppOptions struct {
	Root string
	// Start is run.start, run as written. Empty asks GritQA to work it out, which
	// today means a PHP front controller.
	Start string
	// Docroot is the directory holding the front controller, relative to Root or
	// absolute. Empty means Root.
	Docroot string
	Port    int
	Env     map[string]string
	// Ready is a "GET /health" probe. Empty settles for anything answering.
	Ready string
}

// App is the process GritQA started. It is never the user's own server: their
// Apache keeps serving their real database, untouched, on its own port.
type App struct {
	BaseURL string
	// Generated is true when GritQA wrote the entry point itself, which is worth
	// saying out loud in the transcript.
	Generated bool

	cmd  *exec.Cmd
	once sync.Once
	done chan struct{}
	tail *ring
}

// StartApp launches the API pointed at the sandbox. The user's tree is never
// written to: a generated router lives in the sandbox's temp directory.
func (s *Sandbox) StartApp(ctx context.Context, opts AppOptions) (*App, error) {
	port := opts.Port
	if port == 0 {
		var err error
		if port, err = freePort(); err != nil {
			return nil, err
		}
	}

	line, generated, err := s.entryPoint(opts, port)
	if err != nil {
		return nil, err
	}

	name, flag := "sh", "-c"
	if runtime.GOOS == "windows" {
		name, flag = "cmd", "/c"
	}
	cmd := exec.Command(name, flag, line)
	cmd.Dir = opts.Root
	cmd.Env = s.environ(opts.Env)

	tail := &ring{max: 20}
	cmd.Stdout, cmd.Stderr = tail, tail
	setpgid(cmd)
	if err := cmd.Start(); err != nil {
		return nil, err
	}

	app := &App{
		BaseURL:   fmt.Sprintf("http://%s:%d", loopback, port),
		Generated: generated,
		cmd:       cmd,
		done:      make(chan struct{}),
	}
	app.tail = tail
	go func() {
		cmd.Wait()
		close(app.done)
	}()

	if err := app.await(ctx, opts.Ready, 20*time.Second); err != nil {
		app.Stop()
		return nil, err
	}
	return app, nil
}

// entryPoint decides what to run. A configured run.start wins; otherwise a PHP
// front controller gets a generated router, because repointing the project's own
// server would mean editing their .env and racing their real work.
func (s *Sandbox) entryPoint(opts AppOptions, port int) (line string, generated bool, err error) {
	if strings.TrimSpace(opts.Start) != "" {
		return opts.Start, false, nil
	}

	doc := opts.Docroot
	if doc == "" {
		doc = opts.Root
	}
	if !filepath.IsAbs(doc) {
		doc = filepath.Join(opts.Root, doc)
	}
	front := "index.php"
	if _, err := os.Stat(filepath.Join(doc, front)); err != nil {
		return "", false, fmt.Errorf("nothing in run.start says how to bring your API up, "+
			"and there is no %s in %s to work it out from", front, doc)
	}

	php, err := phpBinary()
	if err != nil {
		return "", false, err
	}
	router, err := s.writeRouter(doc, front)
	if err != nil {
		return "", false, err
	}
	return fmt.Sprintf("%q -S %s:%d -t %q %q", php, loopback, port, doc, router), true, nil
}

// writeRouter generates the shim that presets the sandbox's DB_* in $_ENV before
// the front controller runs. That hook is the one phpdotenv's immutable loader
// respects: an exported variable is seen by getenv and therefore *skipped*, which
// leaves the app falling through to its own hardcoded default — the user's real
// database. Presetting $_ENV is what actually redirects it, and it writes nothing
// into their tree.
func (s *Sandbox) writeRouter(docroot, front string) (string, error) {
	env, err := json.Marshal(s.Env())
	if err != nil {
		return "", err
	}
	doc, err := json.Marshal(docroot)
	if err != nil {
		return "", err
	}

	body := fmt.Sprintf(`<?php
// Generated by GritQA. Not part of your project, and deleted when the run ends.
$__env = json_decode(%s, true);
foreach ($__env as $k => $v) { $_ENV[$k] = $v; $_SERVER[$k] = $v; putenv("$k=$v"); }
$__doc = %s;
chdir($__doc);
$__path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);
$__file = $__path === null ? false : realpath($__doc . $__path);
if ($__file && is_file($__file) && strncmp($__file, $__doc, strlen($__doc)) === 0
    && substr($__file, -4) !== '.php') {
    return false;
}
require $__doc . '/%s';
`, phpString(string(env)), string(doc), front)

	path := filepath.Join(s.dir, "router.php")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		return "", err
	}
	return path, nil
}

// phpString wraps JSON in single quotes for PHP, which does not interpolate
// inside them, so the JSON's own double quotes and backslashes survive.
func phpString(s string) string {
	return "'" + strings.ReplaceAll(strings.ReplaceAll(s, `\`, `\\`), "'", `\'`) + "'"
}

// phpBinary prefers PATH, then the places a Mac developer's PHP actually lives.
// A bundled stack does not put php on PATH, and failing over that would be a
// confusing way to lose a run.
func phpBinary() (string, error) {
	if p, err := exec.LookPath("php"); err == nil {
		return p, nil
	}
	for _, p := range []string{
		"/Applications/XAMPP/xamppfiles/bin/php",
		"/Applications/MAMP/bin/php/php8.2.0/bin/php",
		"/opt/homebrew/bin/php",
		"/usr/local/bin/php",
	} {
		if info, err := os.Stat(p); err == nil && !info.IsDir() {
			return p, nil
		}
	}
	return "", errors.New("your project looks like PHP and there is no php on your PATH — " +
		"add run.start to .gritqa/config.yaml with the command that serves it")
}

// await waits for the API to answer, and gives up early when the process has
// already died rather than spending the whole timeout on a corpse.
func (a *App) await(ctx context.Context, ready string, limit time.Duration) error {
	method, path := "GET", "/"
	if f := strings.Fields(ready); len(f) == 2 {
		method, path = strings.ToUpper(f[0]), f[1]
	} else if len(f) == 1 {
		path = f[0]
	}

	client := &http.Client{Timeout: 3 * time.Second}
	deadline := time.Now().Add(limit)
	for {
		select {
		case <-a.done:
			return fmt.Errorf("the API exited before it answered: %s", a.tail.last())
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		req, err := http.NewRequestWithContext(ctx, method, a.BaseURL+path, nil)
		if err != nil {
			return err
		}
		if res, err := client.Do(req); err == nil {
			res.Body.Close()
			if ready == "" || res.StatusCode < 400 {
				return nil
			}
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("the API never answered on %s within %s", a.BaseURL, limit)
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(150 * time.Millisecond):
		}
	}
}

// Stop kills the process group. A built-in PHP server spawns workers, and killing
// only the shell would leave the port held.
func (a *App) Stop() error {
	if a == nil || a.cmd == nil || a.cmd.Process == nil {
		return nil
	}
	a.once.Do(func() {
		kill(a.cmd)
		select {
		case <-a.done:
		case <-time.After(3 * time.Second):
		}
	})
	return nil
}

// Tail is the last of the API's own output, for explaining a failure.
func (a *App) Tail() string {
	if a == nil || a.tail == nil {
		return ""
	}
	return a.tail.last()
}

func freePort() (int, error) {
	l, err := net.Listen("tcp", loopback+":0")
	if err != nil {
		return 0, err
	}
	defer l.Close()
	return l.Addr().(*net.TCPAddr).Port, nil
}

// ring keeps the last few lines of a process's output without growing without
// bound over a long run.
type ring struct {
	mu    sync.Mutex
	lines []string
	part  string
	max   int
}

func (r *ring) Write(p []byte) (int, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	r.part += string(p)
	for {
		i := strings.IndexByte(r.part, '\n')
		if i < 0 {
			break
		}
		if line := strings.TrimSpace(r.part[:i]); line != "" {
			r.lines = append(r.lines, line)
			if len(r.lines) > r.max {
				r.lines = r.lines[len(r.lines)-r.max:]
			}
		}
		r.part = r.part[i+1:]
	}
	return len(p), nil
}

func (r *ring) last() string {
	r.mu.Lock()
	defer r.mu.Unlock()
	if len(r.lines) == 0 {
		return "it printed nothing"
	}
	return r.lines[len(r.lines)-1]
}
