import { Section } from '@/components/ui/section';
import { Tabs, type TabItem } from '@/components/ui/tabs';
import { Terminal, type TermLine } from '@/components/ui/terminal';
import { PlanViewer, type PlanStep } from '@/components/ui/plan-viewer';
import { CodeBlock } from '@/components/ui/code-block';
import { SpecList } from '@/components/ui/card';
import { SectionHead, Prose } from '@/components/ui/typography';

/* ── Panel shell ──────────────────────────────────────────────
   Every capability reads the same way: a narrow explanation column
   against the artifact it produces. */

function Panel({
  title,
  body,
  specs,
  children,
}: {
  title: string;
  body: string;
  specs: string[];
  children: React.ReactNode;
}) {
  return (
    <div className="grid gap-x-10 gap-y-10 pt-10 lg:grid-cols-12 lg:pt-14">
      <div className="animate-line flex flex-col gap-6 opacity-0 lg:col-span-4">
        <div className="flex flex-col gap-3">
          <h3 className="font-heading text-[1.375rem] font-semibold tracking-[-0.02em] text-ink">
            {title}
          </h3>
          <Prose>{body}</Prose>
        </div>
        <SpecList items={specs} className="border-t border-rule pt-5" />
      </div>

      <div className="animate-line opacity-0 [animation-delay:100ms] lg:col-span-8">
        {children}
      </div>
    </div>
  );
}

/* ── 01 Discover ──────────────────────────────────────────── */

const DISCOVER: TermLine[] = [
  { kind: 'cmd', text: 'gritqa' },
  { kind: 'info', text: 'walking ./ — 214 files, 18 packages' },
  { kind: 'blank' },
  { kind: 'tree', text: 'router      chi        34 routes' },
  { kind: 'tree', text: 'handlers    net/http   34 matched' },
  { kind: 'tree', text: 'models      gorm       12 structs' },
  { kind: 'tree', text: 'middleware  auth       jwt bearer' },
  { kind: 'tree', text: 'env         .env.example  7 keys', last: true },
  { kind: 'blank' },
  { kind: 'ok', text: 'resolved 34/34 routes to a handler', meta: '0.9s' },
  { kind: 'ok', text: 'inferred request shapes for 31 routes', meta: '1.4s' },
  { kind: 'info', text: '3 routes need a hint — see .gritqa/unresolved.yaml' },
];

/* ── 02 Plan ──────────────────────────────────────────────── */

const PLAN: PlanStep[] = [
  {
    id: 'session',
    name: 'create session',
    method: 'POST',
    path: '/v1/sessions',
    extract: [{ name: 'token', from: 'body.access_token' }],
    assert: ['status == 201'],
    status: 'pass',
  },
  {
    id: 'cart',
    name: 'open cart',
    method: 'POST',
    path: '/v1/carts',
    uses: ['token'],
    extract: [{ name: 'cartId', from: 'body.id' }],
    assert: ['status == 201'],
    status: 'pass',
  },
  {
    id: 'items',
    name: 'add line item',
    method: 'PATCH',
    path: '/v1/carts/{{cartId}}/items',
    uses: ['cartId'],
    assert: ['status == 200', 'body.items[0].qty == 2'],
    status: 'pass',
  },
  {
    id: 'checkout',
    name: 'checkout',
    method: 'POST',
    path: '/v1/checkout',
    uses: ['cartId'],
    assert: ['status == 201', 'body.total == 4998'],
    status: 'fail',
  },
];

/* ── 03 Run ───────────────────────────────────────────────── */

const RUN: TermLine[] = [
  { kind: 'cmd', text: 'gritqa' },
  { kind: 'info', text: 'checkout-flow · 4 steps · http://localhost:8080' },
  { kind: 'blank' },
  { kind: 'ok', text: 'create session', meta: '84ms' },
  { kind: 'ok', text: 'open cart', meta: '61ms' },
  { kind: 'ok', text: 'add line item', meta: '73ms' },
  { kind: 'fail', text: 'checkout', meta: '212ms' },
  { kind: 'blank' },
  { kind: 'out', text: '  assert  status == 201' },
  { kind: 'out', text: '  actual  500 Internal Server Error' },
  { kind: 'out', text: '  body    {"error":"tax_rate is nil"}' },
  { kind: 'out', text: '  trace   checkout.go:118 → tax.Apply' },
  { kind: 'blank' },
  { kind: 'info', text: 'replay this step: gritqa --only checkout --verbose' },
];

/* ── 04 Own ───────────────────────────────────────────────── */

const YAML = `# .gritqa/checkout-flow.yaml
# generated by gritqa — your edits are preserved on the next run
name: checkout-flow
base_url: \${API_URL}

steps:
  - name: create session
    post: /v1/sessions
    body:
      email: ada@example.com
      password: \${TEST_PASSWORD}
    extract:
      token: body.access_token
    assert:
      - status == 201

  - name: open cart
    post: /v1/carts
    auth: bearer \${token}
    extract:
      cartId: body.id
    assert:
      - status == 201
`;

const TABS: TabItem[] = [
  {
    id: 'discover',
    index: '01',
    label: 'Discover',
    panel: (
      <Panel
        title="It reads the code, not a spec you forgot to update"
        body="GritQA parses your router registrations and follows them into the handlers. It learns the shape of every request from the structs and validators you already wrote, so the tests match the API that actually shipped."
        specs={[
          'Static analysis — nothing to instrument, no traffic to record',
          'Path params, query params, headers and bodies resolved per route',
          'Anything ambiguous is written to a hints file instead of guessed',
        ]}
      >
        <Terminal
          lines={DISCOVER}
          meta="discover"
          stagger={70}
          caption="GritQA walks 214 files, identifies the chi router, matches all 34 routes to their handlers, reads 12 GORM models and the JWT auth middleware, then reports that three routes need a manual hint."
        />
      </Panel>
    ),
  },
  {
    id: 'plan',
    index: '02',
    label: 'Plan',
    panel: (
      <Panel
        title="Requests that depend on each other, in the right order"
        body="A single request against an empty database proves nothing. GritQA works out which endpoints feed which — a session before a cart, a cart before a checkout — and threads the real ids and tokens through the chain."
        specs={[
          'Dependency order derived from the handler call graph',
          'Values extracted from live responses, never hardcoded fixtures',
          'Assertions on status, shape and the fields that carry meaning',
        ]}
      >
        <PlanViewer name="checkout-flow" steps={PLAN} duration="430ms" />
      </Panel>
    ),
  },
  {
    id: 'run',
    index: '03',
    label: 'Run',
    panel: (
      <Panel
        title="A failure you can act on before you open the file"
        body="Every step runs against a real server over real HTTP. When one breaks you get the assertion, the response, and the line in your handler that produced it — not a stack trace from inside a test framework."
        specs={[
          'Assertion, actual response and source location in one block',
          'Dependent steps are skipped, not failed, when a parent breaks',
          'Machine-readable output for CI; the same run reproduces locally',
        ]}
      >
        <Terminal
          lines={RUN}
          meta="run · localhost:8080"
          stagger={70}
          stats={[
            { label: 'Passed', value: '3', tone: 'pass' },
            { label: 'Failed', value: '1', tone: 'fail' },
            { label: 'Wall', value: '430ms' },
          ]}
          caption="Running the checkout flow against a local server. Three steps pass; checkout fails because the server returned 500 instead of 201 with the error tax_rate is nil, traced to checkout.go line 118."
        />
      </Panel>
    ),
  },
  {
    id: 'own',
    index: '04',
    label: 'Own',
    panel: (
      <Panel
        title="Plain YAML in your repo, reviewed like any other change"
        body="The generated plan is a file you commit. Edit an assertion, pin a value, delete a step you do not want — the next run reads your version and keeps it. There is no dashboard holding your test suite hostage."
        specs={[
          'One file per flow, diffable in a pull request',
          'Hand edits survive regeneration; nothing is silently overwritten',
          'Secrets stay in the environment, never in the plan',
        ]}
      >
        <CodeBlock
          code={YAML}
          filename=".gritqa/checkout-flow.yaml"
          lang="yaml"
          caption="A generated plan file. It names the flow, reads the base URL from an environment variable, then defines a create-session step that extracts an access token and an open-cart step that authenticates with it."
        />
      </Panel>
    ),
  },
];

export function Features() {
  return (
    <Section id="capabilities" tone="sunken" space="md" divide frame>
      <SectionHead
        index="02"
        eyebrow="Capabilities"
        title="Four things it does, and nothing it does not."
        lead="No agents watching your traffic, no proxy in the request path, no browser recorder. It reads source, writes a plan, runs it, and hands you the file."
        className="max-w-2xl"
      />

      <Tabs items={TABS} label="Product capabilities" className="mt-14 lg:mt-16" />
    </Section>
  );
}
